version: "3"

networks:
  comics:

services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/usr/share/nginx/html
    ports:
      - "8080:80"
    networks:
      - comics
  src:
    build:
      context: .
      dockerfile: ./config/Dockerfile
    restart: always
    expose:
      - "9000"
    volumes:
      - ./src:/usr/share/nginx/html
    networks:
      - comics
  composer:
    image: composer
    volumes:
      - ./src:/app
    command: composer install
